
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:36:27] "[37mPOST /register HTTP/1.1[0m" 201 -
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:36:30] "[33mGET /users HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:36:31] "[33mGET /users HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:36:37] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:38:30] "[33mGET / HTTP/1.1[0m" 404 -
ERROR:db.settings:Exception on /users [GET]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:38:34] "[35m[1mGET /users HTTP/1.1[0m" 500 -
ERROR:db.settings:Exception on /users [GET]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 16:38:35] "[35m[1mGET /users HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:31:47] "[33mPOST /registr HTTP/1.1[0m" 404 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Animal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3249, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1914, in do_init
    self._process_dependent_arguments()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1976, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1881, in entity
    argument = self.argument()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:32:02] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:32:54] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
ERROR:db.settings:Exception on /users [GET]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 29, in get_users
    return User.get_all_users()
AttributeError: type object 'User' has no attribute 'get_all_users'
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:33:55] "[35m[1mGET /users HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:33:58] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Animal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3249, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1914, in do_init
    self._process_dependent_arguments()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1976, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1881, in entity
    argument = self.argument()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:35:17] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:35:22] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Animal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3249, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1914, in do_init
    self._process_dependent_arguments()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1976, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1881, in entity
    argument = self.argument()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:17] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:18] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:18] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:19] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:19] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3245, in configure_mappers
    raise e
sqlalchemy.exc.InvalidRequestError: One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class User->users'. Original exception was: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:20] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
ERROR:db.settings:Exception on /users [GET]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 29, in get_users
    return User.get_all_users()
AttributeError: type object 'User' has no attribute 'get_all_users'
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:36:22] "[35m[1mGET /users HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Animal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3249, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1914, in do_init
    self._process_dependent_arguments()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1976, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1881, in entity
    argument = self.argument()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:38:00] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:38:24] "[37mPOST /register HTTP/1.1[0m" 201 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
ERROR:db.settings:Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 294, in __call__
    x = eval(self.arg, globals(), self._dict)
  File "<string>", line 1, in <module>
NameError: name 'Animal' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/dkulemza/PycharmProjects/finalProject/registration/signup.py", line 15, in register
    User.add_user(request_data['Login'], request_data['Password'], request_data['Address'])
  File "/Users/dkulemza/PycharmProjects/finalProject/db/user_db.py", line 18, in add_user
    new_user = User(login=_login, password=_psswd, address=_address)
  File "<string>", line 2, in __init__
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 376, in _new_state_if_none
    state = self._state_constructor(instance, self)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/instrumentation.py", line 202, in _state_constructor
    self.dispatch.first_init(self, self.class_)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3361, in _event_on_first_init
    configure_mappers()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3249, in configure_mappers
    mapper._post_configure_properties()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 1947, in _post_configure_properties
    prop.init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/interfaces.py", line 196, in init
    self.do_init()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1914, in do_init
    self._process_dependent_arguments()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1976, in _process_dependent_arguments
    self.target = self.entity.persist_selectable
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 855, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1881, in entity
    argument = self.argument()
  File "/Users/dkulemza/PycharmProjects/finalProject/venv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/clsregistry.py", line 306, in __call__
    % (self.prop.parent, self.arg, n.args[0], self.cls)
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class User->users, expression 'Animal' failed to locate a name ("name 'Animal' is not defined"). If this is a class name, consider adding this relationship() to the <class 'db.user_db.User'> class after both dependent classes have been defined.
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:41:48] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:root:POST, http://127.0.0.1:5000/register
INFO:werkzeug:127.0.0.1 - - [20/Feb/2020 18:43:57] "[37mPOST /register HTTP/1.1[0m" 201 -
